let user=null,events=[],notifications=[],filter='all';
const financeEntities=new Set(['purchase_order','invoice','payment']),rfqEntities=new Set(['rfq','rfq_invite','quote']);
async function logout(){await GCH.db.auth.signOut();location.href='./'}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;const {data:p,error}=await GCH.db.from('user_profiles').select('role').eq('id',u.id).maybeSingle();if(error||p?.role!=='admin'){location.href='./';return}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderEvents()});await loadAll()}
async function loadAll(){try{const [e,n]=await Promise.all([GCH.db.from('activity_events').select('*').order('created_at',{ascending:false}).limit(400),GCH.db.from('notifications').select('*').order('created_at',{ascending:false}).limit(100)]);if(e.error)throw e.error;if(n.error)throw n.error;events=e.data||[];notifications=n.data||[];renderMetrics();renderEvents();renderNotifications()}catch(err){console.error(err);document.getElementById('events').innerHTML='<div class="empty">تعذر تحميل سجل العمليات.</div>'}}
function category(e){if(rfqEntities.has(e.entity_type))return'rfq';if(financeEntities.has(e.entity_type))return'finance';if(e.entity_type==='meal_occurrence')return'meal';if(e.entity_type==='provider_review')return'review';if(e.entity_type==='order')return'order';return'other'}
function renderMetrics(){const today=new Date().toDateString(),todayCount=events.filter(e=>new Date(e.created_at).toDateString()===today).length;document.getElementById('mToday').textContent=GCH.number(todayCount);document.getElementById('mQuotes').textContent=GCH.number(events.filter(e=>category(e)==='rfq').length);document.getElementById('mFinance').textContent=GCH.number(events.filter(e=>category(e)==='finance').length);document.getElementById('mMeals').textContent=GCH.number(events.filter(e=>category(e)==='meal').length)}
function renderEvents(){const xs=filter==='all'?events:events.filter(e=>category(e)===filter);document.getElementById('events').innerHTML=xs.length?xs.map(e=>`<div class="event"><b>${GCH.esc(e.title)}</b><small>${GCH.datetime(e.created_at)} · ${GCH.esc(e.entity_type)} · ${GCH.esc(e.event_type)}</small></div>`).join(''):'<div class="empty">لا توجد أحداث ضمن هذا التصنيف.</div>'}
function renderNotifications(){document.getElementById('notifications').innerHTML=notifications.length?notifications.map(n=>`<div class="item"><div><b>${GCH.esc(n.title)}</b><div class="meta">${GCH.datetime(n.created_at)} · ${GCH.esc(n.audience)}${n.body?`<br>${GCH.esc(n.body)}`:''}</div></div><span class="status ${n.read_at?'st-completed':'st-pending'}">${n.read_at?'مقروء':'غير مقروء'}</span></div>`).join(''):'<div class="empty">لا توجد إشعارات بعد.</div>'}
boot();