let currentTab="requests",page=0,pageSize=50,hasNext=false,providersCache=[],mfaFactorId=null;
const titleMap={requests:"طلبات الموقع",orders:"طلبات الشركات",providers:"المزودون",packages:"الباقات",recurring:"الوجبات المتكررة"};
async function login(){const btn=document.getElementById("loginBtn");GCH.setBusy(btn,true);try{const {error}=await GCH.db.auth.signInWithPassword({email:document.getElementById("email").value.trim(),password:document.getElementById("password").value});if(error)throw error;await boot()}catch(e){GCH.msg("authMsg","بيانات الدخول غير صحيحة.")}finally{GCH.setBusy(btn,false)}}
async function logout(){await GCH.db.auth.signOut();location.reload()}
async function boot(){const {data:{user}}=await GCH.db.auth.getUser();if(!user)return;const {data:p,error}=await GCH.db.from("user_profiles").select("role").eq("id",user.id).maybeSingle();if(error)return GCH.msg("authMsg",GCH.genericError(error));if(!p||p.role!=="admin"){await GCH.db.auth.signOut();return GCH.msg("authMsg","هذا الحساب لا يملك صلاحية الإدارة.")}document.getElementById("auth").classList.add("hidden");document.getElementById("header").classList.remove("hidden");document.getElementById("app").style.display="block";await Promise.all([loadStats(),loadProvidersCache(),checkMfa()]);await loadTab()}
async function refresh(){await Promise.all([loadStats(),loadProvidersCache()]);await loadTab()}
async function count(table,filters=[]){let q=GCH.db.from(table).select("*",{count:"exact",head:true});for(const [m,k,v] of filters)q=q[m](k,v);const {count,error}=await q;if(error)throw error;return count||0}
async function loadStats(){try{const [rq,od,pv,pp,pk,rc]=await Promise.all([count("catering_requests"),count("company_orders"),count("catering_providers"),count("catering_providers",[["eq","status","pending"]]),count("catering_packages",[["eq","review_status","pending_review"]]),count("recurring_meal_plans")]);document.getElementById("sRequests").textContent=GCH.number(rq);document.getElementById("sOrders").textContent=GCH.number(od);document.getElementById("sProviders").textContent=GCH.number(pv);document.getElementById("sPendingProviders").textContent=GCH.number(pp);document.getElementById("sPendingPackages").textContent=GCH.number(pk);document.getElementById("sRecurring").textContent=GCH.number(rc)}catch(e){console.error(e)}}
async function loadProvidersCache(){const {data,error}=await GCH.db.from("catering_providers").select("id,name,status").order("name");if(!error)providersCache=data||[]}
function providerOptions(selected=""){return `<option value="">— اختر مزود —</option>`+providersCache.filter(p=>p.status==="approved").map(p=>`<option value="${p.id}" ${p.id===selected?"selected":""}>${GCH.esc(p.name)}</option>`).join("")}
async function loadTab(){document.getElementById("tabTitle").textContent=titleMap[currentTab];document.getElementById("host").innerHTML='<div class="empty">جارٍ التحميل...</div>';const from=page*pageSize,to=from+pageSize;try{let q;if(currentTab==="requests")q=GCH.db.from("catering_requests").select("*").order("created_at",{ascending:false}).range(from,to);if(currentTab==="orders")q=GCH.db.from("company_orders").select("*,companies(name),catering_providers(name)").order("created_at",{ascending:false}).range(from,to);if(currentTab==="providers")q=GCH.db.from("catering_providers").select("*").order("created_at",{ascending:false}).range(from,to);if(currentTab==="packages")q=GCH.db.from("catering_packages").select("*,catering_providers(name,status)").order("created_at",{ascending:false}).range(from,to);if(currentTab==="recurring")q=GCH.db.from("recurring_meal_plans").select("*,companies(name),company_branches(name),catering_providers(name)").order("created_at",{ascending:false}).range(from,to);const {data,error}=await q;if(error)throw error;const rows=data||[];hasNext=rows.length>pageSize;render(rows.slice(0,pageSize));document.getElementById("prevBtn").disabled=page===0;document.getElementById("nextBtn").disabled=!hasNext;document.getElementById("pageInfo").textContent=`صفحة ${GCH.number(page+1)}`}catch(e){console.error(e);document.getElementById("host").innerHTML='<div class="empty">تعذر تحميل البيانات حاليًا.</div>'}}
function table(headers,rows){document.getElementById("host").innerHTML=rows.length?`<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`:'<div class="empty">لا توجد بيانات.</div>'}
function render(rows){if(currentTab==="requests")renderRequests(rows);if(currentTab==="orders")renderOrders(rows);if(currentTab==="providers")renderProviders(rows);if(currentTab==="packages")renderPackages(rows);if(currentTab==="recurring")renderRecurring(rows)}
function reqType(v){return{package:"باقة",custom:"طلب مخصص",employee_meals:"وجبات موظفين"}[v]||v}
function reqStatus(v){return{new:"جديد",matching:"مطابقة مزود",quoted:"وصل عرض",confirmed:"مؤكد",completed:"مكتمل",cancelled:"ملغي",closed:"مغلق"}[v]||v}
function orderStatus(v){return{pending_approval:"بانتظار الموافقة",approved:"جاهز للإسناد",sent_to_provider:"أُرسل للمزود",provider_accepted:"قبله المزود",provider_rejected:"رفضه المزود",completed:"مكتمل",cancelled:"ملغي"}[v]||v}
function renderRequests(xs){table(["النوع","جهة التواصل","التاريخ","الأشخاص","الموقع","الميزانية","الحالة","إجراء"],xs.map(r=>`<tr><td>${reqType(r.request_type)}<br><span class="muted">${GCH.esc(r.source)}</span></td><td><b>${GCH.esc(r.contact_name)}</b><br>${GCH.esc(r.contact_phone)}${r.contact_email?`<br>${GCH.esc(r.contact_email)}`:""}</td><td>${GCH.date(r.event_date)}</td><td>${r.people_count?GCH.number(r.people_count):"—"}</td><td>${GCH.esc(r.location||"—")}</td><td>${r.estimated_total!=null?GCH.money(r.estimated_total):r.budget!=null?GCH.money(r.budget):"—"}</td><td><span class="status st-${r.status}">${reqStatus(r.status)}</span></td><td><select id="req-${r.id}"><option value="new">جديد</option><option value="matching">مطابقة</option><option value="quoted">وصل عرض</option><option value="confirmed">مؤكد</option><option value="completed">مكتمل</option><option value="cancelled">ملغي</option><option value="closed">مغلق</option></select><button class="ghost" onclick="setRequestStatus('${r.id}')">حفظ</button></td></tr>`))}
function renderOrders(xs){table(["الشركة","النوع","التاريخ","الأشخاص","القيمة","الحالة","المزود","إجراء"],xs.map(o=>`<tr><td>${GCH.esc(o.companies?.name||o.company_name_snapshot||"")}</td><td>${GCH.esc(o.order_type)}</td><td>${GCH.datetime(o.event_date)}</td><td>${GCH.number(o.people_count||0)}</td><td>${GCH.money(o.estimated_total||0,"ar",Number(o.estimated_total||0)%1?1:0)}</td><td><span class="status st-${o.status}">${orderStatus(o.status)}</span></td><td>${GCH.esc(o.catering_providers?.name||"—")}</td><td>${["approved","provider_rejected"].includes(o.status)?`<select id="prov-${o.id}">${providerOptions(o.provider_id)}</select><button class="primary" onclick="assignProvider('${o.id}')">إسناد</button>`:""}${o.status==="provider_accepted"?`<button class="ghost" onclick="completeOrder('${o.id}')">مكتمل</button>`:""}</td></tr>`))}
function renderProviders(xs){table(["الاسم","الهاتف","المناطق","المطابخ","السعة","الحالة","إجراء"],xs.map(p=>`<tr><td><b>${GCH.esc(p.name)}</b></td><td>${GCH.esc(p.phone||"")}</td><td>${GCH.esc((p.service_areas||[]).join("، "))}</td><td>${GCH.esc((p.cuisines||[]).join("، "))}</td><td>${GCH.number(p.max_capacity||0)}</td><td><span class="status st-${p.status}">${{pending:"قيد المراجعة",approved:"معتمد",suspended:"موقوف"}[p.status]||p.status}</span></td><td>${p.status!=="approved"?`<button class="primary" onclick="providerStatus('${p.id}','approved')">اعتماد</button>`:`<button class="danger" onclick="providerStatus('${p.id}','suspended')">إيقاف</button>`}</td></tr>`))}
function renderPackages(xs){table(["المزود","الباقة","التصنيف","السعر","النطاق","المراجعة","النشر","إجراء"],xs.map(p=>`<tr><td>${GCH.esc(p.catering_providers?.name||"")}</td><td><b>${GCH.esc(p.name)}</b>${p.name_en?`<br>${GCH.esc(p.name_en)}`:""}</td><td>${GCH.esc(p.category_key||p.category||"")}</td><td>${GCH.money(p.price_per_person||0,"ar",1)}</td><td>${GCH.number(p.min_people)}–${GCH.number(p.max_people)}</td><td><span class="status st-${p.review_status}">${p.review_status}</span></td><td>${p.active?"منشورة":"غير منشورة"}</td><td>${p.review_status==="pending_review"?`<button class="primary" onclick="packageReview('${p.id}',true)">اعتماد ونشر</button><button class="danger" onclick="packageReview('${p.id}',false)">رفض</button>`:p.review_status==="approved"?`<button class="ghost" onclick="togglePackage('${p.id}',${p.active})">${p.active?"إيقاف النشر":"نشر"}</button>`:""}</td></tr>`))}
function renderRecurring(xs){table(["الشركة","الفرع","الموظفون","الجدول","التكلفة","المزود","الحالة","إجراء"],xs.map(r=>`<tr><td>${GCH.esc(r.companies?.name||"")}</td><td>${GCH.esc(r.company_branches?.name||"")}</td><td>${GCH.number(r.employees)}</td><td>${GCH.number(r.days_per_week)} أيام · ${r.delivery_time?String(r.delivery_time).slice(0,5):"—"}<br>${r.start_date?GCH.date(r.start_date):""}</td><td>${r.monthly_estimate?GCH.money(r.monthly_estimate):"—"}</td><td>${GCH.esc(r.catering_providers?.name||"—")}</td><td><span class="status st-${r.status}">${r.status}</span></td><td>${r.status==="pending"?`<select id="recprov-${r.id}">${providerOptions(r.provider_id)}</select><button class="primary" onclick="activateRecurring('${r.id}')">تفعيل</button>`:""}${["active","paused"].includes(r.status)?`<button class="danger" onclick="recStatus('${r.id}','cancelled')">إلغاء</button>`:""}</td></tr>`))}
async function action(fn){try{await fn();await Promise.all([loadStats(),loadProvidersCache()]);await loadTab()}catch(e){console.error(e);alert(GCH.genericError(e))}}
async function setRequestStatus(id){const status=document.getElementById("req-"+id).value;await action(async()=>{const {error}=await GCH.db.from("catering_requests").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error})}
async function assignProvider(id){const provider_id=document.getElementById("prov-"+id).value;if(!provider_id)return alert("اختر مزودًا.");await action(async()=>{const {error}=await GCH.db.from("company_orders").update({provider_id,status:"sent_to_provider",assigned_at:new Date().toISOString()}).eq("id",id);if(error)throw error})}
async function completeOrder(id){await action(async()=>{const {error}=await GCH.db.from("company_orders").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",id);if(error)throw error})}
async function providerStatus(id,status){await action(async()=>{const {error}=await GCH.db.from("catering_providers").update({status}).eq("id",id);if(error)throw error})}
async function packageReview(id,approve){await action(async()=>{const {error}=await GCH.db.from("catering_packages").update({review_status:approve?"approved":"rejected",active:approve}).eq("id",id);if(error)throw error})}
async function togglePackage(id,active){await action(async()=>{const {error}=await GCH.db.from("catering_packages").update({active:!active}).eq("id",id);if(error)throw error})}
async function activateRecurring(id){const provider_id=document.getElementById("recprov-"+id).value;if(!provider_id)return alert("اختر مزودًا.");await action(async()=>{const {error}=await GCH.db.from("recurring_meal_plans").update({provider_id,status:"active"}).eq("id",id);if(error)throw error})}
async function recStatus(id,status){await action(async()=>{const {error}=await GCH.db.from("recurring_meal_plans").update({status}).eq("id",id);if(error)throw error})}
function changePage(delta){page=Math.max(0,page+delta);loadTab()}
document.getElementById("tabs").onclick=e=>{const tab=e.target.dataset.tab;if(!tab)return;document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");currentTab=tab;page=0;loadTab()}
async function checkMfa(){try{const {data:f}=await GCH.db.auth.mfa.listFactors();const verified=(f?.totp||[]).some(x=>x.status==="verified");document.getElementById("mfaStatus").textContent=verified?"2FA: مفعّل":"2FA: غير مفعّل";document.getElementById("mfaStatus").className="status "+(verified?"st-active":"st-pending");document.getElementById("mfaBtn").classList.toggle("hidden",verified)}catch(e){console.error(e);document.getElementById("mfaStatus").textContent="2FA: غير متاح"}}
async function startMfa(){try{const {data,error}=await GCH.db.auth.mfa.enroll({factorType:"totp",friendlyName:"GCH Operations"});if(error)throw error;mfaFactorId=data.id;document.getElementById("mfaQr").src=data.totp.qr_code;GCH.clearMsg("mfaMsg");GCH.openModal("mfaModal")}catch(e){alert(GCH.genericError(e))}}
async function verifyMfa(){const code=document.getElementById("mfaCode").value.trim();if(!mfaFactorId||!/^\d{6}$/.test(code))return GCH.msg("mfaMsg","أدخل رمزًا صحيحًا من 6 أرقام.");try{const {error}=await GCH.db.auth.mfa.challengeAndVerify({factorId:mfaFactorId,code});if(error)throw error;GCH.msg("mfaMsg","تم تفعيل التحقق بخطوتين.",true);await checkMfa();setTimeout(()=>GCH.closeModal("mfaModal"),900)}catch(e){GCH.msg("mfaMsg","الرمز غير صحيح أو انتهت صلاحيته.")}}
GCH.setupModal("mfaModal");GCH.setupEscape();(async()=>{const {data}=await GCH.db.auth.getSession();if(data.session)boot()})();