let user=null,pos=[],invoices=[],payments=[],fees=[],tab='fees',currentInvoice=null;
const invLabels={submitted:'بانتظار الاعتماد',approved:'معتمدة',partially_paid:'مدفوعة جزئيًا',paid:'مدفوعة',rejected:'مرفوضة',cancelled:'ملغاة'};
const poLabels={issued:'صادر',acknowledged:'مستلم',cancelled:'ملغي'};
const feeLabels={pending:'بانتظار اكتمال الصفقة',accrued:'مستحقة',invoiced:'تمت المطالبة',paid:'محصلة',waived:'معفاة'};
async function logout(){await GCH.db.auth.signOut();location.href='./'}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;const {data:p,error}=await GCH.db.from('user_profiles').select('role').eq('id',user.id).maybeSingle();if(error||p?.role!=='admin'){location.href='./';return}GCH.setupModal('paymentModal');GCH.setupEscape();document.getElementById('payDate').value=GCH.minDate();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;renderHost()});await loadAll()}
async function loadAll(){try{const [p,i,py,f]=await Promise.all([
 GCH.db.from('purchase_orders').select('*,companies(name),catering_providers(name),company_orders(order_type)').order('created_at',{ascending:false}).limit(300),
 GCH.db.from('invoices').select('*,companies(name),catering_providers(name),company_orders(order_type)').order('created_at',{ascending:false}).limit(300),
 GCH.db.from('payment_records').select('*,companies(name)').order('payment_date',{ascending:false}).limit(500),
 GCH.db.from('marketplace_fees').select('*,companies(name),catering_providers(name),company_orders(order_type,status,event_date)').order('created_at',{ascending:false}).limit(500)
]);if(p.error)throw p.error;if(i.error)throw i.error;if(py.error)throw py.error;if(f.error)throw f.error;pos=p.data||[];invoices=i.data||[];payments=py.data||[];fees=f.data||[];renderMetrics();renderHost()}catch(e){console.error(e);document.getElementById('host').innerHTML='<div class="empty">تعذر تحميل البيانات.</div>'}}
function sum(xs,key){return xs.reduce((s,x)=>s+Number(x[key]||0),0)}
function renderMetrics(){const activeInv=invoices.filter(x=>!['rejected','cancelled'].includes(x.status)),invTotal=sum(activeInv,'amount'),paid=sum(payments,'amount'),marketActive=fees.filter(x=>x.status!=='waived'),gmv=sum(marketActive,'gross_amount'),feeDue=sum(fees.filter(x=>['accrued','invoiced'].includes(x.status)),'fee_amount'),feePaid=sum(fees.filter(x=>x.status==='paid'),'fee_amount');document.getElementById('mPO').textContent=GCH.number(pos.length);document.getElementById('mInv').textContent=GCH.money(invTotal,'ar',3);document.getElementById('mPaid').textContent=GCH.money(paid,'ar',3);document.getElementById('mOut').textContent=GCH.money(Math.max(0,invTotal-paid),'ar',3);document.getElementById('mGMV').textContent=GCH.money(gmv,'ar',3);document.getElementById('mFeeDue').textContent=GCH.money(feeDue,'ar',3);document.getElementById('mFeePaid').textContent=GCH.money(feePaid,'ar',3)}
function renderHost(){if(tab==='fees')renderFees();else if(tab==='invoices')renderInvoices();else if(tab==='po')renderPO();else renderPayments()}
function renderFees(){const host=document.getElementById('host');if(!fees.length){host.innerHTML='<div class="empty">لا توجد عمولات Marketplace حتى الآن. أول صفقة سوق مختارة ستظهر هنا تلقائيًا.</div>';return}host.innerHTML=`<div class="toolbar"><div><h2>إيراد المنصة من Marketplace</h2><div class="fee-note">العمولة الأساسية 5% من الصفقة المفتوحة. تصبح مستحقة بعد اكتمال الطلب، ثم يمكن تسجيل المطالبة والتحصيل من هنا.</div></div></div><div class="tablewrap"><table><thead><tr><th>المزود</th><th>الشركة</th><th>الصفقة</th><th>GMV</th><th>العمولة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${fees.map(f=>{const rate=(Number(f.fee_rate||0)*100).toFixed(Number(f.fee_rate||0)*100%1?1:0);let actions='';if(f.status==='accrued')actions=`<button class="primary" onclick="markFee('${f.id}','invoiced')">تمت المطالبة</button><button class="danger" onclick="markFee('${f.id}','waived')">إعفاء</button>`;if(f.status==='invoiced')actions=`<button class="primary" onclick="markFee('${f.id}','paid')">تسجيل التحصيل</button><button class="danger" onclick="markFee('${f.id}','waived')">إعفاء</button>`;return `<tr><td><b>${GCH.esc(f.catering_providers?.name||'')}</b></td><td>${GCH.esc(f.companies?.name||'')}</td><td>${GCH.esc(f.company_orders?.order_type||'طلب Marketplace')}<br><span class="muted">${f.company_orders?.event_date?GCH.date(f.company_orders.event_date):''}</span></td><td>${GCH.money(f.gross_amount,'ar',3)}</td><td><b>${GCH.money(f.fee_amount,'ar',3)}</b><br><span class="muted">${rate}%</span></td><td><span class="status st-${f.status}">${feeLabels[f.status]||f.status}</span>${f.paid_at?`<br><span class="muted">${GCH.date(f.paid_at)}</span>`:''}</td><td><div class="actions">${actions}</div></td></tr>`}).join('')}</tbody></table></div>`}
function renderInvoices(){const host=document.getElementById('host');host.innerHTML=invoices.length?`<div class="tablewrap"><table><thead><tr><th>الشركة</th><th>المزود</th><th>الفاتورة</th><th>القيمة</th><th>الاستحقاق</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${invoices.map(i=>{const paid=payments.filter(p=>p.invoice_id===i.id).reduce((s,p)=>s+Number(p.amount||0),0),bal=Math.max(0,Number(i.amount)-paid);return `<tr><td>${GCH.esc(i.companies?.name||'')}</td><td>${GCH.esc(i.catering_providers?.name||'')}</td><td>${GCH.esc(i.invoice_number)}<br><span class="muted">${GCH.esc(i.company_orders?.order_type||'')}</span></td><td>${GCH.money(i.amount,'ar',3)}<br><span class="muted">متبقي ${GCH.money(bal,'ar',3)}</span></td><td>${GCH.date(i.due_date)}</td><td><span class="status st-${i.status}">${invLabels[i.status]||i.status}</span></td><td><div class="actions">${i.status==='submitted'?`<button class="primary" onclick="setInvoice('${i.id}','approved')">اعتماد</button><button class="danger" onclick="setInvoice('${i.id}','rejected')">رفض</button>`:''}${['approved','partially_paid'].includes(i.status)&&bal>0?`<button class="ghost" onclick="openPayment('${i.id}')">دفعة</button>`:''}</div></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">لا توجد فواتير.</div>'}
function renderPO(){document.getElementById('host').innerHTML=pos.length?`<div class="tablewrap"><table><thead><tr><th>PO</th><th>الشركة</th><th>المزود</th><th>الطلب</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody>${pos.map(p=>`<tr><td>${GCH.esc(p.po_number)}</td><td>${GCH.esc(p.companies?.name||'')}</td><td>${GCH.esc(p.catering_providers?.name||'')}</td><td>${GCH.esc(p.company_orders?.order_type||'')}</td><td>${GCH.money(p.total,'ar',3)}</td><td><span class="status st-${p.status}">${poLabels[p.status]||p.status}</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد أوامر شراء.</div>'}
function renderPayments(){document.getElementById('host').innerHTML=payments.length?`<div class="tablewrap"><table><thead><tr><th>الشركة</th><th>المبلغ</th><th>التاريخ</th><th>الطريقة</th><th>المرجع</th></tr></thead><tbody>${payments.map(p=>`<tr><td>${GCH.esc(p.companies?.name||'')}</td><td>${GCH.money(p.amount,'ar',3)}</td><td>${GCH.date(p.payment_date)}</td><td>${GCH.esc(p.method)}</td><td>${GCH.esc(p.reference||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا توجد دفعات.</div>'}
async function markFee(id,status){const label=status==='paid'?'تأكيد تسجيل تحصيل عمولة المنصة؟':status==='waived'?'تأكيد إعفاء هذه العمولة؟':'تأكيد تسجيل مطالبة العمولة؟';if(!confirm(label))return;const patch={status,updated_at:new Date().toISOString(),paid_at:status==='paid'?new Date().toISOString():null};const {error}=await GCH.db.from('marketplace_fees').update(patch).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
async function setInvoice(id,status){const {error}=await GCH.db.from('invoices').update({status}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
function openPayment(id){currentInvoice=invoices.find(x=>x.id===id);if(!currentInvoice)return;const paid=payments.filter(p=>p.invoice_id===id).reduce((s,p)=>s+Number(p.amount||0),0);document.getElementById('payAmount').value=Math.max(0,Number(currentInvoice.amount)-paid).toFixed(3);document.getElementById('payDate').value=GCH.minDate();document.getElementById('payRef').value='';GCH.clearMsg('payMsg');GCH.openModal('paymentModal')}
async function recordPayment(){if(!currentInvoice)return;const amount=Number(document.getElementById('payAmount').value),btn=document.getElementById('payBtn');if(!Number.isFinite(amount)||amount<=0)return GCH.msg('payMsg','أدخل مبلغًا صحيحًا.');GCH.setBusy(btn,true);try{const {error}=await GCH.db.from('payment_records').insert({invoice_id:currentInvoice.id,company_id:currentInvoice.company_id,amount,currency:currentInvoice.currency,payment_date:document.getElementById('payDate').value,method:document.getElementById('payMethod').value,reference:document.getElementById('payRef').value.trim(),recorded_by:user.id});if(error)throw error;GCH.closeModal('paymentModal');await loadAll()}catch(e){GCH.msg('payMsg',GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
boot();