let user=null,providers=[],issues=[],reviews=[];
async function logout(){await GCH.db.auth.signOut();location.href='./'}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;const {data:p,error}=await GCH.db.from('user_profiles').select('role').eq('id',user.id).maybeSingle();if(error||p?.role!=='admin'){location.href='./';return}await loadAll()}
async function loadAll(){try{const today=GCH.minDate();const [pv,oc,rv]=await Promise.all([
 GCH.db.from('catering_providers').select('id,name,status,review_count,average_rating,completed_orders_count,accepted_orders_count,rejected_orders_count,acceptance_rate,on_time_rate,avg_response_minutes,performance_score').eq('status','approved').order('performance_score',{ascending:false}),
 GCH.db.from('meal_plan_occurrences').select('*,companies(name),catering_providers(name),company_branches(name)').lte('service_date',today).in('status',['scheduled','missed']).order('service_date',{ascending:false}).limit(200),
 GCH.db.from('provider_reviews').select('id').limit(1000)
]);if(pv.error)throw pv.error;if(oc.error)throw oc.error;if(rv.error)throw rv.error;providers=pv.data||[];issues=oc.data||[];reviews=rv.data||[];render()}catch(e){console.error(e);alert(GCH.genericError(e))}}
function render(){document.getElementById('mProviders').textContent=GCH.number(providers.length);document.getElementById('mScore').textContent=providers.length?GCH.number(providers.reduce((s,x)=>s+Number(x.performance_score||0),0)/providers.length,1):'—';document.getElementById('mIssues').textContent=GCH.number(issues.length);document.getElementById('mReviews').textContent=GCH.number(reviews.length);renderLeaderboard();renderIssues()}
function renderLeaderboard(){document.getElementById('leaderboard').innerHTML=providers.length?`<div class="tablewrap"><table><thead><tr><th>#</th><th>المزود</th><th>Score</th><th>التقييم</th><th>القبول</th><th>في الوقت</th><th>متوسط الرد</th><th>مكتملة</th></tr></thead><tbody>${providers.map((p,i)=>`<tr><td>${i+1}</td><td><b>${GCH.esc(p.name)}</b></td><td><span class="score">${GCH.number(p.performance_score||50,1)}</span></td><td>${p.review_count?`${GCH.number(p.average_rating,2)}/5 (${GCH.number(p.review_count)})`:'—'}</td><td>${GCH.number(p.acceptance_rate||0,1)}%</td><td>${p.review_count?`${GCH.number(p.on_time_rate||0,1)}%`:'—'}</td><td>${p.avg_response_minutes==null?'—':`${GCH.number(p.avg_response_minutes,0)} د`}</td><td>${GCH.number(p.completed_orders_count||0)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">لا يوجد مزودون معتمدون بعد.</div>'}
function renderIssues(){document.getElementById('issues').innerHTML=issues.length?issues.map(x=>`<div class="item ${x.status==='missed'?'risk':''}"><div><b>${GCH.date(x.service_date)} · ${GCH.esc(x.companies?.name||'شركة')}</b><div class="meta">${GCH.esc(x.catering_providers?.name||'مزود')} · ${GCH.esc(x.company_branches?.name||'')} · ${GCH.number(x.employees)} موظف</div></div><span class="status st-${x.status}">${x.status==='missed'?'تعذر التسليم':'لم يتم تحديثها'}</span></div>`).join(''):'<div class="empty">لا توجد استثناءات تنفيذ حاليًا.</div>'}
boot();