let user=null,company=null,memberRole=null,orders=[],pos=[],invoices=[],payments=[],poCan=false,financeCan=false,currentInvoice=null;
const invoiceLabels={submitted:'بانتظار الاعتماد',approved:'معتمدة',partially_paid:'مدفوعة جزئيًا',paid:'مدفوعة',rejected:'مرفوضة',cancelled:'ملغاة'};
const poLabels={issued:'صادر',acknowledged:'استلمه المزود',cancelled:'ملغي'};
async function logout(){await GCH.db.auth.signOut();location.href='./'}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;await GCH.db.rpc('claim_company_invitation');const {data:c,error}=await GCH.db.from('companies').select('*').limit(1).maybeSingle();if(error||!c){location.href='./';return}company=c;const {data:m}=await GCH.db.from('company_members').select('role,status').eq('company_id',company.id).eq('user_id',user.id).maybeSingle();memberRole=m?.status==='active'?m.role:null;const owner=company.owner_user_id===user.id;poCan=owner||['approver','finance','admin'].includes(memberRole);financeCan=owner||['finance','admin'].includes(memberRole);document.getElementById('companyName').textContent=company.name+' — أوامر الشراء والفواتير والدفعات.';document.getElementById('myRole').textContent=owner?'مالك الحساب':({requester:'مقدم طلبات',approver:'معتمد',finance:'المالية',admin:'مسؤول'}[memberRole]||'عرض فقط');document.getElementById('termsSection').classList.toggle('hidden',!owner);document.getElementById('termsDays').value=company.payment_terms_days??30;GCH.setupModal('paymentModal');GCH.setupEscape();await loadAll()}
async function loadAll(){try{const [o,p,i,py]=await Promise.all([
 GCH.db.from('company_orders').select('id,order_type,event_date,estimated_total,currency,status,provider_id,catering_providers(name)').eq('company_id',company.id).order('created_at',{ascending:false}),
 GCH.db.from('purchase_orders').select('*,company_orders(order_type,event_date),catering_providers(name)').eq('company_id',company.id).order('created_at',{ascending:false}),
 GCH.db.from('invoices').select('*,company_orders(order_type,event_date),catering_providers(name)').eq('company_id',company.id).order('created_at',{ascending:false}),
 GCH.db.from('payment_records').select('*').eq('company_id',company.id).order('payment_date',{ascending:false})
]);if(o.error)throw o.error;if(p.error)throw p.error;if(i.error)throw i.error;if(py.error)throw py.error;orders=o.data||[];pos=p.data||[];invoices=i.data||[];payments=py.data||[];render()}catch(e){console.error(e);alert(GCH.genericError(e))}}
function render(){const orderTotal=orders.filter(x=>x.status!=='cancelled').reduce((s,x)=>s+Number(x.estimated_total||0),0),approvedTotal=invoices.filter(x=>['approved','partially_paid','paid'].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0),paidTotal=payments.reduce((s,x)=>s+Number(x.amount||0),0);document.getElementById('mOrders').textContent=GCH.money(orderTotal,'ar',orderTotal%1?3:0);document.getElementById('mInvoices').textContent=GCH.money(approvedTotal,'ar',approvedTotal%1?3:0);document.getElementById('mPaid').textContent=GCH.money(paidTotal,'ar',paidTotal%1?3:0);document.getElementById('mOutstanding').textContent=GCH.money(Math.max(0,approvedTotal-paidTotal),'ar',3);
 const withPo=new Set(pos.map(x=>x.order_id));const eligible=orders.filter(x=>['provider_accepted','completed'].includes(x.status)&&x.provider_id&&!withPo.has(x.id));document.getElementById('poOrder').innerHTML=eligible.length?eligible.map(x=>`<option value="${x.id}">${GCH.esc(x.order_type)} · ${GCH.esc(x.catering_providers?.name||'مزود')} · ${GCH.money(x.estimated_total||0,'ar',3)}</option>`).join(''):'<option value="">لا توجد طلبات مؤهلة بدون PO</option>';document.getElementById('poBtn').disabled=!poCan||!eligible.length;
 document.getElementById('poList').innerHTML=pos.length?pos.map(po=>`<div class="item"><div><b>${GCH.esc(po.po_number)}</b><div class="meta">${GCH.esc(po.catering_providers?.name||'')} · ${GCH.esc(po.company_orders?.order_type||'')} · ${GCH.money(po.total||0,'ar',3)}<br>صدر: ${GCH.date(po.issued_at)}${po.acknowledged_at?` · استلام: ${GCH.date(po.acknowledged_at)}`:''}</div></div><div class="actions"><span class="status st-${po.status}">${poLabels[po.status]||po.status}</span><a class="ghost" target="_blank" href="../document.html?type=po&id=${encodeURIComponent(po.id)}">طباعة</a>${poCan&&po.status!=='cancelled'?`<button class="danger" onclick="cancelPO('${po.id}')">إلغاء</button>`:''}</div></div>`).join(''):'<div class="empty">لا توجد أوامر شراء بعد.</div>';
 document.getElementById('invoiceList').innerHTML=invoices.length?invoices.map(inv=>{const paid=payments.filter(p=>p.invoice_id===inv.id).reduce((s,p)=>s+Number(p.amount||0),0),bal=Math.max(0,Number(inv.amount)-paid);return `<div class="item"><div><b>فاتورة ${GCH.esc(inv.invoice_number)}</b><div class="meta">${GCH.esc(inv.catering_providers?.name||'')} · ${GCH.money(inv.amount,'ar',3)} · استحقاق ${GCH.date(inv.due_date)}<br>مدفوع ${GCH.money(paid,'ar',3)} · متبقي ${GCH.money(bal,'ar',3)}</div></div><div class="actions"><span class="status st-${inv.status}">${invoiceLabels[inv.status]||inv.status}</span><a class="ghost" target="_blank" href="../document.html?type=invoice&id=${encodeURIComponent(inv.id)}">عرض/طباعة</a>${financeCan&&inv.status==='submitted'?`<button class="primary" onclick="invoiceAction('${inv.id}','approved')">اعتماد</button><button class="danger" onclick="invoiceAction('${inv.id}','rejected')">رفض</button>`:''}${financeCan&&['approved','partially_paid'].includes(inv.status)&&bal>0?`<button class="ghost" onclick="openPayment('${inv.id}')">تسجيل دفعة</button>`:''}</div></div>`}).join(''):'<div class="empty">لا توجد فواتير بعد.</div>';
 document.getElementById('paymentList').innerHTML=payments.length?payments.slice(0,20).map(p=>`<div class="item"><div><b>${GCH.money(p.amount,'ar',3)}</b><div class="meta">${GCH.date(p.payment_date)} · ${GCH.esc(p.method)}${p.reference?` · ${GCH.esc(p.reference)}`:''}</div></div></div>`).join(''):'<div class="empty">لا توجد دفعات مسجلة.</div>'}
async function createPO(){if(!poCan)return;const order_id=document.getElementById('poOrder').value,btn=document.getElementById('poBtn');if(!order_id)return;GCH.setBusy(btn,true);try{const {error}=await GCH.db.from('purchase_orders').insert({company_id:company.id,order_id,po_number:document.getElementById('poNumber').value.trim(),notes:document.getElementById('poNotes').value.trim()});if(error)throw error;GCH.msg('poMsg','تم إصدار أمر الشراء.',true);document.getElementById('poNumber').value='';document.getElementById('poNotes').value='';await loadAll()}catch(e){GCH.msg('poMsg',GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
async function cancelPO(id){if(!confirm('إلغاء أمر الشراء؟'))return;const {error}=await GCH.db.from('purchase_orders').update({status:'cancelled'}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
async function invoiceAction(id,status){const {error}=await GCH.db.from('invoices').update({status}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
function openPayment(id){currentInvoice=invoices.find(x=>x.id===id);if(!currentInvoice)return;const paid=payments.filter(p=>p.invoice_id===id).reduce((s,p)=>s+Number(p.amount||0),0);document.getElementById('payAmount').value=Math.max(0,Number(currentInvoice.amount)-paid).toFixed(3);document.getElementById('payDate').value=GCH.minDate();document.getElementById('payRef').value='';document.getElementById('payNotes').value='';GCH.clearMsg('payMsg');GCH.openModal('paymentModal')}
async function recordPayment(){if(!currentInvoice||!financeCan)return;const amount=Number(document.getElementById('payAmount').value),btn=document.getElementById('payBtn');if(!Number.isFinite(amount)||amount<=0)return GCH.msg('payMsg','أدخل مبلغًا صحيحًا.');GCH.setBusy(btn,true);try{const {error}=await GCH.db.from('payment_records').insert({invoice_id:currentInvoice.id,company_id:company.id,amount,payment_date:document.getElementById('payDate').value,method:document.getElementById('payMethod').value,reference:document.getElementById('payRef').value.trim(),notes:document.getElementById('payNotes').value.trim()});if(error)throw error;GCH.closeModal('paymentModal');await loadAll()}catch(e){GCH.msg('payMsg',GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
async function saveTerms(){if(company.owner_user_id!==user.id)return;const days=Number(document.getElementById('termsDays').value),btn=document.getElementById('termsBtn');if(!Number.isInteger(days)||days<0||days>365)return GCH.msg('termsMsg','أدخل عدد أيام بين 0 و365.');GCH.setBusy(btn,true);try{const {data,error}=await GCH.db.from('companies').update({payment_terms_days:days}).eq('id',company.id).select().single();if(error)throw error;company=data;GCH.msg('termsMsg','تم حفظ شروط الدفع.',true)}catch(e){GCH.msg('termsMsg',GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
boot();