let user=null,company=null,orders=[],payments=[],rfqs=[],quotes=[],reviews=[],occurrences=[],plans=[],ratingValue=0,currentOrder=null;
async function logout(){await GCH.db.auth.signOut();location.href='./'}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;await GCH.db.rpc('claim_company_invitation');const {data:c,error}=await GCH.db.from('companies').select('*').limit(1).maybeSingle();if(error||!c){location.href='./';return}company=c;document.getElementById('companyName').textContent=company.name+' — الإنفاق، الوفورات، أداء المزودين وتنفيذ الوجبات.';GCH.setupModal('reviewModal');GCH.setupEscape();await loadAll()}
async function loadAll(){try{const [o,p,r,q,rv,oc,pl]=await Promise.all([
 GCH.db.from('company_orders').select('id,branch_id,provider_id,order_type,event_date,estimated_total,status,catering_providers(name),company_branches(name)').eq('company_id',company.id).order('created_at',{ascending:false}),
 GCH.db.from('payment_records').select('*').eq('company_id',company.id).order('payment_date',{ascending:false}),
 GCH.db.from('rfqs').select('id,status,selected_quote_id').eq('company_id',company.id),
 GCH.db.from('provider_quotes').select('id,rfq_id,total,status'),
 GCH.db.from('provider_reviews').select('*').eq('company_id',company.id),
 GCH.db.from('meal_plan_occurrences').select('*,catering_providers(name),company_branches(name)').eq('company_id',company.id).gte('service_date',GCH.minDate()).order('service_date').limit(120),
 GCH.db.from('recurring_meal_plans').select('id,status').eq('company_id',company.id).eq('status','active')
]);for(const x of [o,p,r,q,rv,oc,pl])if(x.error)throw x.error;orders=o.data||[];payments=p.data||[];rfqs=r.data||[];quotes=q.data||[];reviews=rv.data||[];occurrences=oc.data||[];plans=pl.data||[];render()}catch(e){console.error(e);alert(GCH.genericError(e))}}
function moneySum(xs,field){return xs.reduce((s,x)=>s+Number(x[field]||0),0)}
function render(){const spend=moneySum(orders.filter(x=>x.status!=='cancelled'),'estimated_total'),paid=moneySum(payments,'amount'),completed=orders.filter(x=>x.status==='completed').length;let savings=0;for(const r of rfqs.filter(x=>x.selected_quote_id)){const qs=quotes.filter(q=>q.rfq_id===r.id&&['submitted','accepted','rejected'].includes(q.status));const selected=quotes.find(q=>q.id===r.selected_quote_id);if(selected&&qs.length>1){const avg=moneySum(qs,'total')/qs.length;savings+=Math.max(0,avg-Number(selected.total||0))}}document.getElementById('mSpend').textContent=GCH.money(spend,'ar',3);document.getElementById('mPaid').textContent=GCH.money(paid,'ar',3);document.getElementById('mSavings').textContent=GCH.money(savings,'ar',3);document.getElementById('mCompleted').textContent=GCH.number(completed);renderRanks();renderReviews();renderMeals()}
function renderRanks(){const byProvider={},byBranch={};for(const o of orders.filter(x=>x.status!=='cancelled')){const p=o.catering_providers?.name||'غير معيّن',b=o.company_branches?.name||'بدون فرع',v=Number(o.estimated_total||0);byProvider[p]=(byProvider[p]||0)+v;byBranch[b]=(byBranch[b]||0)+v}const rows=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="rank"><span>${GCH.esc(k)}</span><b>${GCH.money(v,'ar',3)}</b></div>`).join('')||'<div class="empty">لا توجد بيانات بعد.</div>';document.getElementById('providerSpend').innerHTML=rows(byProvider);document.getElementById('branchSpend').innerHTML=rows(byBranch)}
function renderReviews(){const done=new Set(reviews.map(x=>x.order_id)),queue=orders.filter(x=>x.status==='completed'&&x.provider_id&&!done.has(x.id));document.getElementById('reviewQueue').innerHTML=queue.length?queue.map(o=>`<div class="item"><div><b>${GCH.esc(o.catering_providers?.name||'مزود')}</b><div class="meta">${GCH.esc(o.order_type)} · ${GCH.date(o.event_date)} · ${GCH.money(o.estimated_total||0,'ar',3)}</div></div><button class="primary" onclick="openReview('${o.id}')">تقييم</button></div>`).join(''):'<div class="empty">لا توجد طلبات مكتملة بانتظار التقييم.</div>'}
function openReview(id){currentOrder=orders.find(x=>x.id===id);if(!currentOrder)return;ratingValue=0;document.getElementById('reviewTitle').textContent=(currentOrder.catering_providers?.name||'المزود')+' — '+currentOrder.order_type;document.getElementById('quality').value='';document.getElementById('communication').value='';document.getElementById('onTime').value='';document.getElementById('reviewComment').value='';GCH.clearMsg('reviewMsg');renderStars();GCH.openModal('reviewModal')}
function renderStars(){document.getElementById('ratingStars').innerHTML=[1,2,3,4,5].map(n=>`<button type="button" class="${n<=ratingValue?'on':''}" onclick="setRating(${n})" aria-label="${n} stars">★</button>`).join('')}
function setRating(n){ratingValue=n;renderStars()}
async function submitReview(){if(!currentOrder||!ratingValue)return GCH.msg('reviewMsg','اختر تقييمًا من 1 إلى 5.');const btn=document.getElementById('reviewBtn'),on=document.getElementById('onTime').value;GCH.setBusy(btn,true);try{const {error}=await GCH.db.from('provider_reviews').insert({order_id:currentOrder.id,company_id:company.id,provider_id:currentOrder.provider_id,rating:ratingValue,quality_rating:document.getElementById('quality').value||null,communication_rating:document.getElementById('communication').value||null,on_time:on===''?null:on==='true',comment:document.getElementById('reviewComment').value.trim()});if(error)throw error;GCH.closeModal('reviewModal');await loadAll()}catch(e){GCH.msg('reviewMsg',GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
function renderMeals(){document.getElementById('mealList').innerHTML=occurrences.length?occurrences.map(x=>`<div class="item"><div><b>${GCH.date(x.service_date)} · ${String(x.delivery_time||'').slice(0,5)}</b><div class="meta">${GCH.esc(x.company_branches?.name||'')} · ${GCH.esc(x.catering_providers?.name||'مزود')} · ${GCH.number(x.employees)} موظف${x.provider_notes?`<br>${GCH.esc(x.provider_notes)}`:''}</div></div><div class="actions"><span class="status st-${x.status}">${{scheduled:'مجدولة',delivered:'تم التسليم',confirmed:'مؤكدة',missed:'لم تُسلّم',cancelled:'ملغاة'}[x.status]||x.status}</span>${x.status==='delivered'?`<button class="primary" onclick="setOccurrence('${x.id}','confirmed')">تأكيد الاستلام</button>`:''}${x.status==='scheduled'?`<button class="danger" onclick="setOccurrence('${x.id}','cancelled')">إلغاء هذا اليوم</button>`:''}</div></div>`).join(''):'<div class="empty">لا توجد عمليات وجبات مجدولة حاليًا.</div>'}
async function setOccurrence(id,status){if(status==='cancelled'&&!confirm('إلغاء وجبات هذا اليوم؟'))return;const {error}=await GCH.db.from('meal_plan_occurrences').update({status}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
async function generateMeals(){try{for(const p of plans)await GCH.db.rpc('generate_meal_occurrences',{p_plan_id:p.id,p_days:45});await loadAll()}catch(e){alert(GCH.genericError(e))}}
boot();