let user=null,company=null,members=[],canManage=false;
const roleLabels={requester:'مقدم طلبات',approver:'معتمد طلبات',finance:'المالية',admin:'مسؤول الشركة'};
const statusLabels={invited:'دعوة معلقة',active:'فعال',disabled:'موقوف'};
async function logout(){await GCH.db.auth.signOut();location.href='./'}
function toggleLimit(){document.getElementById('limitWrap').classList.toggle('hidden',document.getElementById('iRole').value!=='approver')}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;await GCH.db.rpc('claim_company_invitation');const {data:c,error}=await GCH.db.from('companies').select('*').limit(1).maybeSingle();if(error||!c){location.href='./';return}company=c;document.getElementById('companyName').textContent=company.name+' — إدارة أعضاء الحساب وصلاحياتهم.';await loadAll()}
async function loadAll(){const {data,error}=await GCH.db.from('company_members').select('*').eq('company_id',company.id).order('created_at');if(error){document.getElementById('members').innerHTML='<div class="empty">تعذر تحميل الفريق.</div>';return}members=data||[];const me=members.find(x=>x.user_id===user.id&&x.status==='active');canManage=company.owner_user_id===user.id||me?.role==='admin';document.getElementById('myRole').textContent=company.owner_user_id===user.id?'مالك الحساب':roleLabels[me?.role]||'عضو';document.getElementById('inviteSection').classList.toggle('hidden',!canManage);render()}
function render(){document.getElementById('members').innerHTML=members.length?members.map(m=>`<div class="member-row"><div><b>${GCH.esc(m.full_name||m.email)}</b><div class="meta">${GCH.esc(m.email)} · ${statusLabels[m.status]||m.status}</div></div><select id="role-${m.id}" ${!canManage?'disabled':''} onchange="roleChanged('${m.id}')"><option value="requester" ${m.role==='requester'?'selected':''}>Requester</option><option value="approver" ${m.role==='approver'?'selected':''}>Approver</option><option value="finance" ${m.role==='finance'?'selected':''}>Finance</option><option value="admin" ${m.role==='admin'?'selected':''}>Admin</option></select><input id="limit-${m.id}" type="number" min="0" step=".1" placeholder="حد الاعتماد" value="${m.approval_limit??''}" ${(!canManage||m.role!=='approver')?'disabled':''}><div class="member-actions">${canManage?`<button class="ghost" onclick="saveMember('${m.id}')">حفظ</button>${m.status==='active'?`<button class="danger" onclick="disableMember('${m.id}')">إيقاف</button>`:`<button class="danger" onclick="deleteMember('${m.id}')">حذف</button>`}`:''}</div></div>`).join(''):'<div class="empty">لا يوجد أعضاء مضافون بعد.</div>'}
function roleChanged(id){const role=document.getElementById('role-'+id).value;document.getElementById('limit-'+id).disabled=role!=='approver'}
async function inviteMember(){if(!canManage)return;const email=document.getElementById('iEmail').value.trim().toLowerCase(),full_name=document.getElementById('iName').value.trim(),role=document.getElementById('iRole').value,approval_limit=role==='approver'?document.getElementById('iLimit').value:null,btn=document.getElementById('inviteBtn');if(!email.includes('@'))return GCH.msg('inviteMsg','أدخل بريدًا إلكترونيًا صحيحًا.');GCH.setBusy(btn,true,'جارٍ إرسال الدعوة...');try{const {data:{session}}=await GCH.db.auth.getSession();const r=await fetch(`${GCH.url}/functions/v1/company-invite`,{method:'POST',headers:{apikey:GCH.key,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({company_id:company.id,email,full_name,role,approval_limit})});const out=await r.json();if(!r.ok)throw new Error(out.error||'invite_failed');GCH.msg('inviteMsg',out.email_sent?'تمت إضافة العضو وإرسال الدعوة بالبريد.':'تمت إضافة الدعوة، لكن تعذر إرسال البريد حاليًا.',true);document.getElementById('iEmail').value='';document.getElementById('iName').value='';await loadAll()}catch(e){console.error(e);GCH.msg('inviteMsg',e.message==='already_active'?'هذا البريد عضو فعال أصلًا.':GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
async function saveMember(id){const role=document.getElementById('role-'+id).value,approval_limit=role==='approver'?(document.getElementById('limit-'+id).value||null):null;const {error}=await GCH.db.from('company_members').update({role,approval_limit}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
async function disableMember(id){if(!confirm('إيقاف وصول هذا العضو؟'))return;const {error}=await GCH.db.from('company_members').update({status:'disabled'}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
async function deleteMember(id){if(!confirm('حذف هذه الدعوة؟'))return;const {error}=await GCH.db.from('company_members').delete().eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
toggleLimit();boot();