let user=null,provider=null,orders=[],pos=[],invoices=[],payments=[];
const poLabels={issued:'صادر',acknowledged:'تم الاستلام',cancelled:'ملغي'};const invLabels={submitted:'بانتظار الاعتماد',approved:'معتمدة',partially_paid:'مدفوعة جزئيًا',paid:'مدفوعة',rejected:'مرفوضة',cancelled:'ملغاة'};
async function logout(){await GCH.db.auth.signOut();location.href='./'}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;const {data:p,error}=await GCH.db.from('catering_providers').select('*').eq('owner_user_id',user.id).maybeSingle();if(error||!p){location.href='./';return}provider=p;document.getElementById('providerStatus').textContent=provider.status==='approved'?'مزود معتمد':'الحساب '+provider.status;document.getElementById('providerStatus').className='status '+(provider.status==='approved'?'st-approved':'st-pending');document.getElementById('invDate').value=GCH.minDate();await loadAll()}
async function loadAll(){try{const [o,p,i,py]=await Promise.all([
 GCH.db.from('company_orders').select('id,company_id,order_type,event_date,estimated_total,currency,status,company_name_snapshot').eq('provider_id',provider.id).in('status',['provider_accepted','completed']).order('created_at',{ascending:false}),
 GCH.db.from('purchase_orders').select('*,company_orders(order_type,event_date,company_name_snapshot)').eq('provider_id',provider.id).order('created_at',{ascending:false}),
 GCH.db.from('invoices').select('*,company_orders(order_type,event_date,company_name_snapshot)').eq('provider_id',provider.id).order('created_at',{ascending:false}),
 GCH.db.from('payment_records').select('*').order('payment_date',{ascending:false})
]);if(o.error)throw o.error;if(p.error)throw p.error;if(i.error)throw i.error;if(py.error)throw py.error;orders=o.data||[];pos=p.data||[];invoices=i.data||[];payments=(py.data||[]).filter(x=>invoices.some(i=>i.id===x.invoice_id));render()}catch(e){console.error(e);alert(GCH.genericError(e))}}
function render(){document.getElementById('mPO').textContent=GCH.number(pos.length);const invTotal=invoices.reduce((s,x)=>s+Number(x.amount||0),0),paid=payments.reduce((s,x)=>s+Number(x.amount||0),0);document.getElementById('mInv').textContent=GCH.money(invTotal,'ar',3);document.getElementById('mPaid').textContent=GCH.money(paid,'ar',3);
 document.getElementById('poList').innerHTML=pos.length?pos.map(po=>`<div class="item"><div><b>${GCH.esc(po.po_number)}</b><div class="meta">${GCH.esc(po.company_orders?.company_name_snapshot||'شركة')} · ${GCH.esc(po.company_orders?.order_type||'')} · ${GCH.money(po.total||0,'ar',3)}<br>${GCH.date(po.issued_at)}</div></div><div class="actions"><span class="status st-${po.status}">${poLabels[po.status]||po.status}</span><a class="ghost" target="_blank" href="../document.html?type=po&id=${encodeURIComponent(po.id)}">طباعة</a>${po.status==='issued'?`<button class="primary" onclick="ackPO('${po.id}')">تأكيد الاستلام</button>`:''}</div></div>`).join(''):'<div class="empty">لا توجد أوامر شراء حتى الآن.</div>';
 document.getElementById('invoiceList').innerHTML=invoices.length?invoices.map(inv=>{const got=payments.filter(p=>p.invoice_id===inv.id).reduce((s,p)=>s+Number(p.amount||0),0);return `<div class="item"><div><b>فاتورة ${GCH.esc(inv.invoice_number)}</b><div class="meta">${GCH.esc(inv.company_orders?.company_name_snapshot||'شركة')} · ${GCH.money(inv.amount,'ar',3)} · استحقاق ${GCH.date(inv.due_date)}<br>مستلم ${GCH.money(got,'ar',3)}</div></div><div class="actions"><span class="status st-${inv.status}">${invLabels[inv.status]||inv.status}</span><a class="ghost" target="_blank" href="../document.html?type=invoice&id=${encodeURIComponent(inv.id)}">عرض/طباعة</a></div></div>`}).join(''):'<div class="empty">لم تصدر أي فاتورة بعد.</div>';
 const existingByOrder=new Set(invoices.map(x=>x.order_id));const eligible=orders.filter(x=>!existingByOrder.has(x.id));document.getElementById('invOrder').innerHTML=eligible.length?eligible.map(o=>`<option value="${o.id}">${GCH.esc(o.company_name_snapshot||'شركة')} · ${GCH.esc(o.order_type)} · ${GCH.money(o.estimated_total||0,'ar',3)}</option>`).join(''):'<option value="">لا يوجد طلب جاهز للفوترة</option>';document.getElementById('invBtn').disabled=provider.status!=='approved'||!eligible.length;orderChanged();
 document.getElementById('paymentList').innerHTML=payments.length?payments.slice(0,20).map(p=>`<div class="item"><div><b>${GCH.money(p.amount,'ar',3)}</b><div class="meta">${GCH.date(p.payment_date)} · ${GCH.esc(p.method)}${p.reference?` · ${GCH.esc(p.reference)}`:''}</div></div></div>`).join(''):'<div class="empty">لا توجد دفعات مستلمة بعد.</div>'}
function orderChanged(){const id=document.getElementById('invOrder').value,o=orders.find(x=>x.id===id);document.getElementById('invAmount').value=o?Number(o.estimated_total||0).toFixed(3):'';const matching=pos.filter(p=>p.order_id===id&&p.status!=='cancelled');document.getElementById('invPO').innerHTML='<option value="">بدون PO</option>'+matching.map(p=>`<option value="${p.id}">${GCH.esc(p.po_number)}</option>`).join('')}
async function ackPO(id){const {error}=await GCH.db.from('purchase_orders').update({status:'acknowledged'}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
async function createInvoice(){const order_id=document.getElementById('invOrder').value,o=orders.find(x=>x.id===order_id),amount=Number(document.getElementById('invAmount').value),invoice_number=document.getElementById('invNumber').value.trim(),btn=document.getElementById('invBtn');if(!o||!invoice_number||!Number.isFinite(amount)||amount<=0)return GCH.msg('invMsg','أكمل رقم الفاتورة والمبلغ بشكل صحيح.');GCH.setBusy(btn,true);try{const purchase_order_id=document.getElementById('invPO').value||null;const {error}=await GCH.db.from('invoices').insert({company_id:o.company_id,order_id,purchase_order_id,provider_id:provider.id,invoice_number,amount,issue_date:document.getElementById('invDate').value,notes:document.getElementById('invNotes').value.trim()});if(error)throw error;GCH.msg('invMsg','تم إرسال الفاتورة للشركة.',true);document.getElementById('invNumber').value='';document.getElementById('invNotes').value='';await loadAll()}catch(e){GCH.msg('invMsg',GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
boot();