let user=null,provider=null,reviews=[],occurrences=[],plans=[],currentOccurrence=null;
async function logout(){await GCH.db.auth.signOut();location.href='./'}
async function boot(){const {data:{user:u}}=await GCH.db.auth.getUser();if(!u){location.href='./';return}user=u;const {data:p,error}=await GCH.db.from('catering_providers').select('*').eq('owner_user_id',user.id).maybeSingle();if(error||!p){location.href='./';return}provider=p;document.getElementById('providerName').textContent=provider.name+' — التقييمات، سرعة الاستجابة، القبول والالتزام بالتسليم.';GCH.setupModal('deliveryModal');GCH.setupEscape();await loadAll()}
async function loadAll(){try{const {data:p,error:pe}=await GCH.db.from('catering_providers').select('*').eq('id',provider.id).single();if(pe)throw pe;provider=p;const [rv,oc,pl]=await Promise.all([
 GCH.db.from('provider_reviews').select('*').eq('provider_id',provider.id).order('created_at',{ascending:false}).limit(100),
 GCH.db.from('meal_plan_occurrences').select('*,companies(name),company_branches(name)').eq('provider_id',provider.id).gte('service_date',GCH.minDate()).order('service_date').limit(120),
 GCH.db.from('recurring_meal_plans').select('id,status').eq('provider_id',provider.id).eq('status','active')
]);if(rv.error)throw rv.error;if(oc.error)throw oc.error;if(pl.error)throw pl.error;reviews=rv.data||[];occurrences=oc.data||[];plans=pl.data||[];render()}catch(e){console.error(e);alert(GCH.genericError(e))}}
function pct(v){return `${GCH.number(Number(v||0),1)}%`}
function render(){document.getElementById('mScore').textContent=GCH.number(provider.performance_score||50,1);document.getElementById('mRating').textContent=provider.review_count?`${GCH.number(provider.average_rating,2)} / 5`:'—';document.getElementById('mAccept').textContent=pct(provider.acceptance_rate);document.getElementById('mOnTime').textContent=provider.review_count?pct(provider.on_time_rate):'—';document.getElementById('mResponse').textContent=provider.avg_response_minutes==null?'—':`${GCH.number(provider.avg_response_minutes,0)} دقيقة`;document.getElementById('reviewCount').textContent=`${GCH.number(provider.review_count||0)} مراجعات`;renderReviews();renderMeals()}
function renderReviews(){document.getElementById('reviewList').innerHTML=reviews.length?reviews.map(r=>`<div class="review"><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><div class="meta">${GCH.date(r.created_at)}${r.quality_rating?` · جودة ${r.quality_rating}/5`:''}${r.communication_rating?` · تواصل ${r.communication_rating}/5`:''}${r.on_time!=null?` · ${r.on_time?'في الوقت':'متأخر'}`:''}</div>${r.comment?`<div style="margin-top:7px">${GCH.esc(r.comment)}</div>`:''}</div>`).join(''):'<div class="empty">لا توجد مراجعات بعد.</div>'}
function renderMeals(){document.getElementById('mealList').innerHTML=occurrences.length?occurrences.map(x=>`<div class="item"><div><b>${GCH.date(x.service_date)} · ${String(x.delivery_time||'').slice(0,5)}</b><div class="meta">${GCH.esc(x.companies?.name||'شركة')} · ${GCH.esc(x.company_branches?.name||'')} · ${GCH.number(x.employees)} وجبة${x.provider_notes?`<br>${GCH.esc(x.provider_notes)}`:''}</div></div><div class="actions"><span class="status st-${x.status}">${{scheduled:'مجدولة',delivered:'بانتظار تأكيد الشركة',confirmed:'مؤكدة',missed:'لم تُسلّم',cancelled:'ملغاة'}[x.status]||x.status}</span>${x.status==='scheduled'?`<button class="primary" onclick="openDelivery('${x.id}')">تم التسليم</button><button class="danger" onclick="markMissed('${x.id}')">تعذر التسليم</button>`:''}</div></div>`).join(''):'<div class="empty">لا توجد تسليمات مجدولة.</div>'}
function openDelivery(id){currentOccurrence=occurrences.find(x=>x.id===id);if(!currentOccurrence)return;document.getElementById('deliveryTitle').textContent=`${GCH.date(currentOccurrence.service_date)} · ${currentOccurrence.companies?.name||''}`;document.getElementById('deliveryNotes').value='';GCH.clearMsg('deliveryMsg');GCH.openModal('deliveryModal')}
async function markDelivered(){if(!currentOccurrence)return;const btn=document.getElementById('deliveryBtn');GCH.setBusy(btn,true);try{const {error}=await GCH.db.from('meal_plan_occurrences').update({status:'delivered',provider_notes:document.getElementById('deliveryNotes').value.trim()}).eq('id',currentOccurrence.id);if(error)throw error;GCH.closeModal('deliveryModal');await loadAll()}catch(e){GCH.msg('deliveryMsg',GCH.genericError(e))}finally{GCH.setBusy(btn,false)}}
async function markMissed(id){if(!confirm('تسجيل أن التسليم تعذر لهذا اليوم؟'))return;const {error}=await GCH.db.from('meal_plan_occurrences').update({status:'missed'}).eq('id',id);if(error)return alert(GCH.genericError(error));await loadAll()}
async function generateMeals(){try{for(const p of plans)await GCH.db.rpc('generate_meal_occurrences',{p_plan_id:p.id,p_days:45});await loadAll()}catch(e){alert(GCH.genericError(e))}}
boot();